# Generated by Django 3.0.4 on 2020-04-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('node_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='V2XMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='V2XSIM.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='V2XSIM.Node')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='V2XSIM.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField()),
                ('time', models.DateField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='V2XSIM.V2XMessage')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='V2XSIM.Node')),
            ],
        ),
    ]
